### ISSUE TITLE
SSO for dotnet

### ISSUE THREAD

**Issue by H-Nguyenx** [graphcomment/sso#1]
I use the code for donet but there was error print in the console:
`{"gcCode":410,"msg":"sso data you provided is invalid, please check the documentation on how to encode sso data"}`

**Comment by ddtraceweb** [comment]
Hello, can we see more of your implementation code ?

Thanks.

**Comment by H-Nguyenx** [comment]
I have created a support thread on support.graphcomment.com

My site id is “khucamdia”
This is how I config:

```
window.gc_params = {
graphcomment_id: ‘khucamdia’,
fixed_header_height: 0,
api_public_key: ‘BM95qEjtIXc3fthJpfoBV4pXuQPdamW3 4DrsRa8jqdREl228nM=’,

sso_data: ‘eyJpZCI6MTUsInVzZXJuYW1lIjoiaHVuZ3Rlc3QiLCJlbWFpbCI6Imh1bmdudkBiYW1idS5jb20udm4iLCJwaWN0dXJlIjoiaHR0cHM6Ly9raHVjYW1kaWEuY29tL2ltYWdlcy91c2Vycy9odW5nbnZAYmFtYnUuY29tLnZuIn0= 2B93E6C15CDBB49C0D11F94F9D56D5F24737FC3D 1587864367.54357’
};

(function () {
var gc = document.createElement(‘script’); gc.type = ‘text/javascript’; gc.async = true;
gc.src = ‘https://graphcomment.com/js/integration.js?’ Math.round(Math.random() * 1e8);
(document.getElementsByTagName(‘head’)[0] || document.getElementsByTagName(‘body’)[0]).appendChild(gc);
})();
```

The browser sent this xhr to graphcomment server:
`{"key":{"pubKey":"BM95qEjtIXc3fthJpfoBV4pXuQPdamW3+4DrsRa8jqdREl228nM=","auth":"eyJpZCI6MTUsInVzZXJuYW1lIjoiaHVuZ3Rlc3QiLCJlbWFpbCI6Imh1bmdudkBiYW1idS5jb20udm4iLCJwaWN0dXJlIjoiaHR0cHM6Ly9raHVjYW1kaWEuY29tL2ltYWdlcy91c2Vycy9odW5nbnZAYmFtYnUuY29tLnZuIn0= 8BB08B180C0DCD7905C3B03799AC02FA3749958A 1587865843"}}`
And the server return this:
`{“gcCode”:410,”msg”:”route need authentication – route expired”}`

**Comment by ddtraceweb** [comment]
at end of you sso_data, we generate a timestamp, it's must be in GMT +0. The request is valid for last 5 minutes.

**Comment by H-Nguyenx** [comment]
Thanks, I've fixed the time. Could you help me with this?
Now the browser sent:
`{"key":{"pubKey":"BM95qEjtIXc3fthJpfoBV4pXuQPdamW3+4DrsRa8jqdREl228nM=","auth":"eyJpZCI6IjE1IiwidXNlcm5hbWUiOiJodW5ndGVzdCIsImVtYWlsIjoiaHVuZ252QGJhbWJ1LmNvbS52biIsImxhbmd1YWdlIjoidmkiLCJwaWN0dXJlIjoiaHR0cHM6Ly9raHVjYW1kaWEuY29tL2ltYWdlcy91c2Vycy9udWxsLmdpZiJ9 5F58AE3ADFB6C29E6FEAB63705BCF1D57682DFFE 1588006157"}}`

And the return was:
`{"gcCode":410,"msg":"sso data you provided is invalid, please check the documentation on how to encode sso data"}`

I think I have the sso data right. Here it was:
```
				window.gc_params = {
					graphcomment_id: 'khucamdia',

					// if your website has a fixed header, indicate it's height in pixels
					fixed_header_height: 0,

					api_public_key: 'BM95qEjtIXc3fthJpfoBV4pXuQPdamW3+4DrsRa8jqdREl228nM=',
					sso_data: 'eyJpZCI6IjE1IiwidXNlcm5hbWUiOiJodW5ndGVzdCIsImVtYWlsIjoiaHVuZ252QGJhbWJ1LmNvbS52biIsImxhbmd1YWdlIjoidmkiLCJwaWN0dXJlIjoiaHR0cHM6Ly9raHVjYW1kaWEuY29tL2ltYWdlcy91c2Vycy9udWxsLmdpZiJ9 5F58AE3ADFB6C29E6FEAB63705BCF1D57682DFFE 1588006157'
				};
```

**Comment by ddtraceweb** [comment]
Have you used your secret key api to generate sso data ?

**Comment by H-Nguyenx** [comment]
I forgot to paste in secret key api. Now I have but it still shown error
`{"key":{"pubKey":"BM95qEjtIXc3fthJpfoBV4pXuQPdamW3+4DrsRa8jqdREl228nM=","auth":"eyJpZCI6IjE1IiwidXNlcm5hbWUiOiJodW5ndGVzdCIsImVtYWlsIjoiaHVuZ252QGJhbWJ1LmNvbS52biIsImxhbmd1YWdlIjoiIiwicGljdHVyZSI6Imh0dHBzOi8va2h1Y2FtZGlhLmNvbS9pbWFnZXMvdXNlcnMvbnVsbC5naWYifQ== F5A26F1BD5B69BE8E00E9A03818765C7B42698A4 1588063818"}}`

`{"gcCode":410,"msg":"sso data you provided is invalid, please check the documentation on how to encode sso data"}`

**Comment by ddtraceweb** [comment]
ok, i had found, sorry for the inconvenience.

in this line

return Message + " " + ByteToString(hashedMessage) + " " + Timestamp;

ByteToString(hashedMessage) you must .ToLower() the chain.

**Comment by H-Nguyenx** [comment]
Thank you very much 💯
